name: Ci

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  verify:
    name: â˜‘ï¸ Verify
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: â¬‡ï¸ Clone repository
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: ğŸŸ¢ Install Bun
        uses: oven-sh/setup-bun@v2

      - name: ğŸŸ¢ Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: âŒ› Run Install
        run: "deno --allow-read --allow-env --allow-run run scripts/_runInstall.ts"
      - name: ğŸ§ª Run Test
        run: "deno --allow-read --allow-env --allow-run run scripts/_runTest.ts"
